version: "3.9"

services:
  app:
    build: .
    container_name: php-laboratory-app
    user: "1000:1000"
    volumes:
      - ./apps:/app
    ports:
      - 8000:8000
    networks:
      - php-laboratory

networks:
  php-laboratory:
    name: php-laboratory-network
    driver: bridge
