version: "3.9"

services:
  app:
    build: .
    container_name: php-laboratory-app
    user: "1000:1000"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    networks:
      - php-laboratory
  mysql:
    image: mysql:8.0
    container_name: php-laboratory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: superstar
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql/live_data:/var/lib/mysql
      - ./mysql/backup:/backup
    networks:
      - php-laboratory
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 20s
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: php-laboratory-pma
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
    networks:
      - php-laboratory
    depends_on:
      mysql:
        condition: service_healthy

networks:
  php-laboratory:
    name: php-laboratory-network
    driver: bridge
